include_guard(GLOBAL)
#YOU SPLIT OFF YOUR CMAKE AND PYTHON FILES INTO THEIR OWN REPOSITORIES FOR EASIER FOCUS DURING THEIR DEVELOPMENT. SMART MOVE, BUT DON'T FORGET TO GLUE THE PROJECT BACK TOGETHER.
#This whole file needs to be rewritten to programmatically get these values instead.


#file(REAL_PATH "${CMAKE_CURRENT_LIST_DIR}/../.." PROJECT_BASE)
#message(STATUS "PROJECT_BASE: ${PROJECT_BASE}")
##include(${PROJECT_BASE}/os_host_setup.cmake)

#file(REAL_PATH "${PROJECT_BASE}/scripts" SCRIPTS_DIR)
#message(STATUS "SCRIPTS_DIR: ${SCRIPTS_DIR}")

#file(REAL_PATH "${SCRIPTS_DIR}/cmake" CMAKE_SCRIPTS_DIR)
#message(STATUS "CMAKE_SCRIPTS_DIR: ${CMAKE_SCRIPTS_DIR}")
